name = "Zinée Town"
author = "AD"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "658aa8891989c1584dc6ccc0c85874846d7fba3ff3590100694ff44a39b8e285"

[versions]
fabric = "0.17.0"
minecraft = "1.20.1"
