name = "Zinée Town 1.0.10"
author = "AD"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1c5314d042d8c5446a40d296aa0d516f0b9574c346685fcb7ba552f161a28b4"

[versions]
fabric = "0.17.0"
forge = "47.4.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "fabric", "forge", "neoforge"]
