name = "Zinée Town 1.0.7"
author = "AD"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdc774f33ac12a5eee4000d65fa09ae64d5e7897d1159b1dad3415b3d92179c1"

[versions]
fabric = "0.17.0"
forge = "47.4.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "fabric", "forge", "neoforge"]
