name = "Zinée Town 1.0.9"
author = "AD"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d45c00a3b98dfc235e5266ed7e04930414f9a068d8730efb0f9aeb4ae33ed636"

[versions]
fabric = "0.17.0"
forge = "47.4.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "fabric", "forge", "neoforge"]
