name = "Zinée Town 1.0.11"
author = "AD"
version = "1.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "147f3c3134f5df41990d7e8230e2220cbf3a17e927a078ec18a442c55c304734"

[versions]
fabric = "0.17.0"
forge = "47.4.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "fabric", "forge", "neoforge"]
