name = "Zinée Town 1.0.7"
author = "AD"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9092b033298bb590419f03ddbd7425d6e5b1321e0a6aa73d9915e29085153460"

[versions]
fabric = "0.17.0"
forge = "47.4.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "fabric", "forge", "neoforge"]
