name = "Zinée Town 1.0.10"
author = "AD"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a79770b60411b0ff970b67a7e6cda8afc86fb5b2a9e6194fa415192d3db19846"

[versions]
fabric = "0.17.0"
forge = "47.4.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "fabric", "forge", "neoforge"]
