name = "Zinée Town"
author = "AD"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f694af9e0bb1e1e2aaca1c36c52eb8cd5154b72f31678ba210b7725d714d20c"

[versions]
fabric = "0.17.0"
minecraft = "1.20.1"
