name = "Zinée Town 1.0.12"
author = "AD"
version = "1.0.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a757c6a49ebe7a4f4a0e39dfba7fc24ef11ec367d818c8daba02a8e98799ce2"

[versions]
fabric = "0.17.0"
forge = "47.4.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "fabric", "forge", "neoforge"]
