name = "Zinée Town 1.0.9"
author = "AD"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3aa21a90b67b03c7664f9c7319378ca636ac512f011bee69a79434bbda58409a"

[versions]
fabric = "0.17.0"
forge = "47.4.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "fabric", "forge", "neoforge"]
