name = "Zinée Town 1.0.8"
author = "AD"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e67803829bf53068d5640c110cbcf6cea8d6694e4e9b095324ff3f8e1e49d65"

[versions]
fabric = "0.17.0"
forge = "47.4.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "fabric", "forge", "neoforge"]
