name = "Zinée Town 1.0.7"
author = "AD"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18dd3ad901f17a8f965557d62568aa51715c796905c3db2bc4ec34b6b76ddf7b"

[versions]
fabric = "0.17.0"
forge = "47.4.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "fabric", "forge", "neoforge"]
