name = "Zinée Town"
author = "AD"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db91c53baf39b8b9b852a0b40813342d30f56e77e1be826299ed6bb6663412b9"

[versions]
fabric = "0.17.0"
minecraft = "1.20.1"
