name = "Zinée Town"
author = "AD"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b86c589149ceebfc547e7ca5109399659ca2992e13c92cedbb07decbfd2947b6"

[versions]
fabric = "0.17.0"
minecraft = "1.20.1"
